---
# tasks file for server
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest
  notify:
    - restart apache2
- name: enabled apache2 mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

