variable "aws_region" {
   description = "AWS Region to launch servers"
   default = "us-east-1"
}

variable "aws_access_key" {
   description = "AWS User Access Key"
   default = "ASIA324INWZWC2V3MXOQ"
}

variable "aws_secret_key" {
   description = "AWS User Secret Key"
   default = "lnRhQkiLTslF98Akl0TXwlhDRhgQpFr2cA2SEP6V"
}

variable "aws_api_token" {
   description = "AWS API Token"
   default = "FwoGZXIvYXdzEHsaDFpfzmt4Tvk/N8H0DSK1ATfJjC29QxVbs9GGghzBZdsQ/QbLaBF0AHH2cbDqQTia8mNLrZArbWz10MxF1pRu94BGWTiXJ9qcYdx9VkwqswIgR+27cY+Gc0OzHSu9gKQOba0AniwB+P5ql4IKKvKLUOGSyChCQvDXulZfTuzGoA7WVZkASeouV0Z+esfMZuyziednxZiElgqR++w2aiv7ACWUh3bt3YHkah/KHyl/zV0uQPMk6yusNBZqoEigYBDx6vHJVToo2aa1lwYyLeLQJFM9KdlPoRYQKTmOjG0oPPgs1S5dScSsZQ6usZvRrXEM/Cgkt3aJgkRQaw=="
}

variable "aws_amis" {
   default = {
       us-east-1 = "ami-09d56f8956ab235b3"
       eu-west-2 = "ami-0ee8244746ec5d6d4"
   }
}

variable "instance_type" {
   description = "Type of AWS EC2 instance."
   default     = "t2.micro"
}

variable "ssh_user" {
   type        = string
   description = "Default user for EC2 instance."
   default     = "ubuntu"
}

variable "generated_key_name" {
  type        = string
  default     = "tf-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "project_path" {
   type        = string
   description = "Project directory"
   default     = "/home/labsuser/Wordpress-with-Ansible"
}

variable "instance_count" {
   default = 1
}
