variable "aws_region" {
   description = "AWS Region to launch servers"
   default = "us-east-1"
}

variable "aws_access_key" {
   description = "AWS User Access Key"
   default = "ASIA324INWZWPH5RJNLI"
}

variable "aws_secret_key" {
   description = "AWS User Secret Key"
   default = "iYpQaOSXt/9O/+YWT0IQM7Ae4e8YpQlvzjaewh7n"
}

variable "aws_api_token" {
   description = "AWS API Token"
   default = "FwoGZXIvYXdzEHEaDBN2mi5eHBMYq1mymiK1AYGICOqNByrd9A/wxomuvfUpKKksW2FLPn2ZmyZsKmK/IIabV4pnGCwTduLF8dHL7XNFuo3zn7B9znmmJ0Gaxi6mlyYhv0pFayObK4zhU0UbkszguWQp0N5l6ZfQuo2ZH1oefjCE5MBFP2/SK+EkrdCXS9wtwySILlqPFLJlvlHYbVmP9qPLFmyDjZKWtQFVSQKZijSRCxM5aYCdr1J/7AJywos1x8ozxBSwFm4/MtXqN6L/vpUouomzlwYyLRZwqhxPh0IFt8+37R/3hLdTxMaD/wh/AtBAlptqyDrvtFCLQrYJF/D73lBoHw=="
}

variable "aws_amis" {
   default = {
       us-east-1 = "ami-09d56f8956ab235b3"
       eu-west-2 = "ami-0ee8244746ec5d6d4"
   }
}

variable "instance_type" {
   description = "Type of AWS EC2 instance."
   default     = "t2.micro"
}

variable "ssh_user" {
   type        = string
   description = "Default user for EC2 instance."
   default     = "ubuntu"
}

variable "generated_key_name" {
  type        = string
  default     = "tf-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "project_path" {
   type        = string
   description = "Project directory"
   default     = "/home/labsuser/Wordpress-with-Ansible"
}

variable "instance_count" {
   default = 1
}
