variable "aws_region" {
   description = "AWS Region to launch servers"
   default = "us-east-1"
}

variable "aws_access_key" {
   description = "AWS User Access Key"
   default = "ASIA324INWZWCAPEJTYP"
}

variable "aws_secret_key" {
   description = "AWS User Secret Key"
   default = "73BrrM82jBu6sY31YfvgUErPIZKV7V0oMN8BlDyt"
}

variable "aws_api_token" {
   description = "AWS API Token"
   default = "FwoGZXIvYXdzEGUaDCwOvJIgdF4OF3riDyK1Aacd1Dh5ceyqfatLlYFdBJImTkkg9umR7IHcUoywGvtiIx6BsWVwe9k0bcBmpKFdfTx6Ikguu1j6E0gm531p4IlVk+brqufZcdxj5gX5Jk1M5DfZkulUO1zXhO5H/Wu3OM8dxhJ3/Hi6IsbMieDETVVYIR4iJm5+7GlQpItMznhpVRh0ExM0q3jtQDz9pZvkTuHjqa0hgsiTNCeOmIAm/k4ZMYexA5hghYhJz38XvcGvOIc77wAosbCwlwYyLdA2TxXgFmSex07xeMK702G1hXZHGzXuYVLISjA6FdgKumJBOiX3Xhe4lHPO3g=="
}

variable "aws_amis" {
   default = {
       us-east-1 = "ami-09d56f8956ab235b3"
       eu-west-2 = "ami-0ee8244746ec5d6d4"
   }
}

variable "instance_type" {
   description = "Type of AWS EC2 instance."
   default     = "t2.micro"
}

variable "generated_key_name" {
  type        = string
  default     = "tf-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "instance_count" {
   default = 1
}
