---
# tasks file for mysql
- name: Install MySQL DB server
  become: true
  apt:
    name: mysql-server
    state: latest
- name: install python-mysql package
  apt:
    name: python3-pymysql
    update_cache: 'yes'
    cache_valid_time: 86400
    state: present
  become: true
- name: Create mysql database
  mysql_db: 
    name: "{{ wp_mysql_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
- name: Create mysql user
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
