---
# tasks file for php
- name: install software-properties-common
  apt: name=software-properties-common
  become: true
- name: add ppa repository for php 7.4
  apt_repository: 'repo="ppa:ondrej/php"'
  become: true
  
- name: update apt repositories
  apt: update_cache=yes
  become: true
  
- name: install php 7.4
  apt: name=php7.4
  state: present
  become: true
  
- name: install php dependencies for LAMP stack
  apt:
    pkg:
      - php7.4-cli
      - php7.4-common
      - php7.4-mysql
      - php7.4-curl
      - php7.4-json
      - php7.4-cgi
      - php7.4-xsl
      - php7.4-cgi
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-xmlrpc
      - php7.4-soap
      - php7.4-intl
      - libapache2-mod-php
    state: present
    update_cache: 'yes'
  become: true
