---
# tasks file for php
- name: install software-properties-common
  apt: name=software-properties-common
  become: true
- name: add ppa repository for php 7.4
  apt_repository: 'repo="ppa:ondrej/php"'
  become: true
- name: update apt repositories
  apt: update_cache=yes
  become: true
  
- name: install php dependencies for LAMP stack
  apt:
    pkg:
      pkg: ['php-pear', 'php-fpm', 'php-dev', 'php-zip', 'php-curl',
          'php-xmlrpc', 'php-gd', 'php-mysql', 'php-mbstring', 'php-xml', 'php-mysql']
    state: present
    update_cache: 'yes'
  become: true
